# config.yaml (Revised for Hierarchy)

# --- Top Level WACN Definition ---
wacn:
  id: 90210 # The Wide Area Communications Network ID

  # --- Zones (RFSS) are defined under the WACN ---
  zones:
    101: # Zone/RFSS ID (This is also the System ID)
      alias: "Metropolis Public Safety"
      area:
        top_left:
          latitude: 45.5
          longitude: -76.0
        bottom_right:
          latitude: 45.0
          longitude: -75.0

      # --- Sites are defined within a Zone ---
      sites:
        1:
          alias: "Downtown Core"
          assignment_mode: "balanced"
          subsites:
            - id: 1001
              alias: "Tower A"
              location:
                latitude: 45.42
                longitude: -75.69
          channels:
            1: { freq_tx: 150.0, freq_rx: 155.0, enabled: true, fdma: true, tdma: true, control: true }
            2: { freq_tx: 151.0, freq_rx: 156.0, enabled: true, fdma: true, tdma: true, voice: true }
        2:
          alias: "East Suburbs"
          assignment_mode: "rollover"
          subsites:
            - id: 2001
              alias: "Tower B"
              location:
                latitude: 45.40
                longitude: -75.50
          channels:
            1: { freq_tx: 152.0, freq_rx: 157.0, enabled: true, fdma: true, tdma: true, control: true }

      # --- Resources like TGs and Units belong to the Zone ---
      talkgroups:
        1001: { alias: "Dispatch 1", mode: "mixed", hangtime: 2000, ptt_id: false }
        1002: { alias: "Tac 1", mode: "tdma", hangtime: 3000, ptt_id: true }

      consoles:
        2001: # Console ID
          alias: "Dispatch Console 1"
          # A list of talkgroup IDs this console can monitor and use.
          # For now, it can access all talkgroups in this zone.
          affiliated_talkgroup_ids: [1001, 1002]

      units:
        1: { alias: "Unit A", tdma_capable: true }
        2: { alias: "Unit B", tdma_capable: false }

    501: # Zone/RFSS ID (This is also the System ID)
      alias: "Undergroup System"
      area:
        top_left:
          latitude: 45.5
          longitude: -76.0
        bottom_right:
          latitude: 45.0
          longitude: -75.0

      # --- Sites are defined within a Zone ---
      sites:
        1:
          alias: "Downtown Core"
          assignment_mode: "balanced"
          subsites:
            - id: 1001
              alias: "Tower A"
              location:
                latitude: 45.42
                longitude: -75.69
          channels:
            1: { freq_tx: 150.0, freq_rx: 155.0, enabled: true, fdma: true, tdma: true, control: true }
            2: { freq_tx: 151.0, freq_rx: 156.0, enabled: true, fdma: true, tdma: true, voice: true }
        2:
          alias: "East Suburbs"
          assignment_mode: "rollover"
          subsites:
            - id: 2001
              alias: "Tower B"
              location:
                latitude: 45.40
                longitude: -75.50
          channels:
            1: { freq_tx: 152.0, freq_rx: 157.0, enabled: true, fdma: true, tdma: true, control: true }

      # --- Resources like TGs and Units belong to the Zone ---
      talkgroups:
        1001: { alias: "Dispatch 1", mode: "mixed", hangtime: 2000, ptt_id: false }
        1002: { alias: "Tac 1", mode: "tdma", hangtime: 3000, ptt_id: true }

      units:
        1: { alias: "Unit A", tdma_capable: true }
        2: { alias: "Unit B", tdma_capable: false }
