# config.yaml (Revised for Hierarchy)

# --- Top Level WACN Definition ---
wacn:
  id: 781824 # The Wide Area Communications Network ID

  # --- Zones (RFSS) are defined under the WACN ---
  zones:
    1: # Zone/RFSS ID (This is also the System ID)
      alias: "DuPage County - Simulcast"
      area:
        top_left:
          latitude: 45.424236903015014
          longitude: -76.47388938771302
        bottom_right:
          latitude: 45.25226317908509
          longitude: -75.0596182014537

      # --- Sites are defined within a Zone ---
      sites:
        1:
          alias: "Core"
          assignment_mode: "balanced"
          subsites:
            - id: 1001
              alias: "Tower A"
              location:
                latitude: 45.43688000584178
                longitude: -75.612003419383
              operating_radius: 25.6
          channels:
            1: { freq_tx: 769.16875, freq_rx: 794.16875, enabled: true, fdma: true, tdma: true, control: true, data: false }
            2: { freq_tx: 769.33125, freq_rx: 794.33125, enabled: true, fdma: true, tdma: false, voice: true, data: false }
            3: { freq_tx: 769.46875, freq_rx: 794.46875, enabled: true, fdma: false, tdma: true, voice: true, data: true }
        2:
          alias: "East Suburbs"
          assignment_mode: "rollover"
          subsites:
            - id: 2001
              alias: "Tower B"
              location:
                latitude: 45.42507447278771
                longitude: -75.69984962753956
              operating_radius: 5
          channels:
            1: { freq_tx: 769.75625, freq_rx: 794.16875, enabled: true, fdma: true, tdma: true, control: true, data: false }
            2: { freq_tx: 770.05625, freq_rx: 795.33125, enabled: true, fdma: true, tdma: false, control: false, voice: true, data: false }

      talkgroups:
        1001: { alias: "Dispatch 1", mode: "mixed", hangtime: 2000, ptt_id: false }
        1002: { alias: "Tac 1", mode: "tdma", hangtime: 3000, ptt_id: true }

      consoles:
        2001: # Console ID
          alias: "Dispatch Console 1"
          # A list of talkgroup IDs this console can monitor and use.
          # For now, it can access all talkgroups in this zone.
          affiliated_talkgroup_ids: [1001, 1002]

      units:
        1: { alias: "Unit A", tdma_capable: true }
        2: { alias: "Unit B", tdma_capable: false }

    2: # Zone/RFSS ID (This is also the System ID)
      alias: "Undergroup System"
      area:
        top_left:
          latitude: 45.33242480607971
          longitude: -75.69217582695931
        bottom_right:
          latitude: 45.311522687875424
          longitude: -75.62969897689878

      # --- Sites are defined within a Zone ---
      sites:
        1:
          alias: "Airport Core"
          assignment_mode: "balanced"
          subsites:
            - id: 1001
              alias: "Tower Site"
              location:
                latitude: 45.322915763262166
                longitude: -75.662691882764
              operating_radius: 5.1
          channels:
            1: { freq_tx: 150.0, freq_rx: 155.0, enabled: true, fdma: true, tdma: true, control: true }
            2: { freq_tx: 151.0, freq_rx: 156.0, enabled: true, fdma: true, tdma: true, voice: true }

      # --- Resources like TGs and Units belong to the Zone ---
      talkgroups:
        1001: { alias: "Dispatch 1", mode: "mixed", hangtime: 2000, ptt_id: false }
        1002: { alias: "Tac 1", mode: "tdma", hangtime: 3000, ptt_id: true }

      units:
        1: { alias: "Unit A", tdma_capable: true }
        2: { alias: "Unit B", tdma_capable: false }
